Improvement/attachments and requests
backtrace-labs/backtrace-cocoa pull request #147
Opened 2024-12-18 00:09 UTC by melekr

ref: BT-5311

2025-01-07 09:40 UTC, konraddysput requested changes
The pull request description doesn't tell me why exactly we need it. Can you please share more thoughts on this?

2025-01-07 09:40 UTC, konraddysput commented on Examples/Example-iOS-ObjC/ViewController.m
> -
small nit: 
it's better to not include changes that don't belong to the pull request or adds additional work for reviewers

2025-01-07 09:40 UTC, konraddysput commented on Package.swift
> +        .macOS(.v11),
why do we want to bump the macos target?

2025-01-07 09:40 UTC, konraddysput commented on Sources/Public/BacktraceCrashReporter.swift
> +        let reportData: Data
why - generateLiveReport allows to pass nullable exception - why it matters?

2025-01-07 09:40 UTC, konraddysput commented on Sources/Features/Network/MultipartRequest.swift
> +        let tempURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(UUID().uuidString)
what happen to the file if the app is restarted while file is being created?

2025-01-07 09:40 UTC, konraddysput commented on Sources/Features/Network/MultipartRequest.swift
> +            writeToFile(fileHandle, "\(attribute.value)\r\n")
shouldn't we do one write operation instead of multiple? I know opening writing and closing cost resources and time

2025-01-07 17:20 UTC, melekr commented on Examples/Example-iOS-ObjC/ViewController.m
> -
oops

2025-01-07 21:19 UTC, melekr commented on Package.swift
> +        .macOS(.v11),
macos 11 is way past its end of life, this was a perfect opportunity to let it go.
Next bump should be : 
```
.iOS(.v13),
.macOS(.v12),
.tvOS(.v13)
```

2025-01-07 21:50 UTC, melekr commented on Sources/Features/Network/MultipartRequest.swift
> +        let tempURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(UUID().uuidString)
file is created in Temp directory managed by OS, if the app is restarted there is no guarantee the file is persisted but : 
- OOM : MultipartRequest will be retried/reconstructed from the already generated and persisted live report.
- BacktraceReport/Resource :  MultipartRequest will be retried/reconstructed from repository
- Watcher: MultipartRequest will be retried/reconstructed from repository

2025-01-07 22:10 UTC, melekr commented on Sources/Features/Network/MultipartRequest.swift
> +            writeToFile(fileHandle, "\(attribute.value)\r\n")
My intention was multiple small write operations with batched writes to reduce system overhead, i'll look into it.

2025-01-07 22:24 UTC, melekr commented on Sources/Features/Network/MultipartRequest.swift
> +        let tempURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(UUID().uuidString)
unlike NSMutableData it's even possible to recover multipart request file! (not sure if necessary but can be a good excuse to consider for `// TODO: T16698 - Add retry logic`)

2025-01-09 09:30 UTC, konraddysput commented on Sources/Features/Network/MultipartRequest.swift
> +            writeToFile(fileHandle, "\(attribute.value)\r\n")
hmm i think it would be faster if we create a string with attributes in memory and then do one write operation. There is no chance we will oom the app via string with attributes so we should be good to go

2025-01-10 18:36 UTC, melekr commented on Sources/Features/Network/MultipartRequest.swift
> -            body.append(attachment.data)
we can use a [Stream](https://developer.apple.com/documentation/foundation/inputstream).
Benefits:
- no longer holds attachment or report data in memory before writing since data is written directly to file handle as it's being read
- Data is never loaded entirely into memory, great for multiple and/or large attachments
Caviats:
- Memory and buffer management
- Error handling (incomplete streams, stream cannot be opened
- Small buffer chunks

2025-01-14 21:49 UTC, melekr commented on Sources/Public/BacktraceCrashReporter.swift
> +        let reportData: Data
for testing, will remove.

2025-01-14 22:30 UTC, melekr commented
Holding data in memory for attributes or attachments changes the purpose of writing into files.
A hybrid approach would be buffering data in chunks, using a buffered stream.

2025-01-14 22:44 UTC, melekr commented on Package.swift
> +        .macOS(.v11),
reverted

2025-01-16 12:09 UTC, konraddysput commented on Sources/Features/Error/BacktraceError.swift
> +            return "File Write Error occurred."
Suggestion: 

I think file is to generic and might be weird from the developer perspective that the file means a temporary file during HTTP submission. My recommendation is to make it more explicit by saying "Temporary submission file" instead.

2025-01-16 12:09 UTC, konraddysput commented on Sources/Features/Network/MultipartRequest.swift
> +                throw HttpError.fileCreationFailed(tempURL)
it won't be captured by the L:111 - which means we will return a generic error rather this this one?

2025-01-16 12:09 UTC, konraddysput commented on Sources/Features/Network/MultipartRequest.swift
> +            var reportString = "--\(boundary)\r\n"
It would be better if we start with report rather than with attributes - if the application stops during submission part, we can still submit a valid report.

2025-01-16 12:09 UTC, konraddysput commented on Sources/Features/Network/MultipartRequest.swift
> +                try writeToFile(fileHandle, "Content-Type: \(attachment.mimeType)\r\n\r\n")
I think we should do it with a single write

2025-01-16 12:09 UTC, konraddysput commented on Sources/Features/Network/MultipartRequest.swift
> +                fileHandle.write(attachment.data)
you're making an attachment copy in the temporary file. WE cannot stream a file directory from the file available somewhere?

2025-01-16 12:59 UTC, melekr commented on Sources/Features/Error/BacktraceError.swift
> +            return "File Write Error occurred."
yes, it looks out of place
also need to properly handle an 'attachmentError'.

2025-01-16 16:37 UTC, melekr commented on Sources/Features/Network/MultipartRequest.swift
> +                fileHandle.write(attachment.data)
possible but requires creating an InputStream for each attachments.
If we decide to keep files, i'll make the necessary improvements.

2025-01-16 16:41 UTC, melekr commented
- file handling, cleaning and integrity checks to be added id we decide to keep it.
- Error granularity improvements to be added

2025-01-17 09:59 UTC, perf2711 commented on Sources/Features/Error/BacktraceError.swift
> +            return "Provided URL cannot be parsed: \(url)."
small nit: can we either get rid of trailing dots or put the URL in quotes?
this goes for every description that has some data displayed in the string

2025-01-17 09:59 UTC, perf2711 commented on Sources/Features/Network/MultipartRequest.swift
> +            multipartRequest.httpBodyStream = InputStream(url: tempURL)
Instead of creating the file and setting it as `httpBodyStream`, couldn't you write directly to the request?

I'm not proficient in Swift, but I found this:
https://developer.apple.com/documentation/foundation/url_loading_system/uploading_streams_of_data

You can use bound streams to achieve that, it seems.

2025-01-17 15:24 UTC, melekr commented on Sources/Features/Network/MultipartRequest.swift
> +            multipartRequest.httpBodyStream = InputStream(url: tempURL)
we can, this is the the approach I was referencing:
> Holding data in memory for attributes or attachments changes the purpose of writing into files. A hybrid approach would be buffering data in chunks, using a buffered stream.

2025-01-20 08:26 UTC, konraddysput commented on Sources/Features/Network/MultipartRequest.swift
> +                let bytesWritten = data.withUnsafeBytes {
why do we need to execute this part of the code in the sync context? You won't submit two identical reports.

2025-01-20 08:26 UTC, konraddysput commented on Sources/Features/Network/MultipartRequest.swift
> +            guard let data = outputStream.property(forKey: .dataWrittenToMemoryStreamKey) as? Data else {
do we read data from the output stream here?

2025-06-12 22:03 UTC, closed without merging